server:
  port: 8089
  
spring:
  data:
    cassandra:
     port: 9042
     keyspace-name: containers
     schema-action: CREATE_IF_NOT_EXISTS
     local-datacenter: datacenter1

url : http://localhost:8089/api/bookings/checkAvailable
